$font = JetBrainsMono Nerd Font, monospace

background {
    monitor =
    color = rgba(0, 0, 0, 1)
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgba(255, 255, 255, 0.9)
    position = 0, 200
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 20
    font_family = $font
    color = rgba(255, 255, 255, 0.5)
    position = 0, 130
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 300, 60
    position = 0, -100
    halign = center
    valign = center
    outline_thickness = 2
    dots_spacing = 0.2
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    fail_text = <span fgcolor="#ff0000"><i>{fail_text}</i></span>
    check_color = rgba(0, 255, 0, 0.6)
}
