general {
    lock_cmd = ~/.config/scripts/swaylock-blur.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 1500  # 25 minutes
    on-timeout = hyprctl keyword monitor "" dpms off
    on-resume = hyprctl keyword monitor "" dpms on
}

listener {
    timeout = 600  # 10 minutes
    on-timeout = ~/.config/scripts/swaylock-blur.sh
    on-resume = hyprctl keyword monitor "" dpms on
}
